name: sparkify-churn-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - pandas=1.2.0
  - pip=20.3.3
  - pip:
    - pyspark==3.0.0
    - streamlit==1.1.0
    - ua-parser==0.10.0
    - user-agents==2.2.0
