name: sparkify-churn-prediction
channels:
  - conda-forge
  - main
  - defaults
dependencies:
  - python=3.7.9
  - java-1.8.0-openjdk-cos7-s390x=1.8.0.242.b08=2
  - pandas=1.2.0
  - pip=20.3.3
  - pip:
    - pyspark==2.4.4
    - streamlit==1.1.0
    - ua-parser==0.10.0
    - user-agents==2.2.0
